firstPress = true;	
ds_grid_clear(aboutToClearGrid,0);
ds_grid_clear(aboutToResetGrid,0);
ds_grid_clear(clearedGrid,0);
ds_grid_clear(mineEaseGrid,0);
ds_list_clear(mineEaseList);
ds_list_clear(resetEaseList);
ds_list_clear(flagEaseList);
ds_grid_clear(removeEaseGrid,0);
ds_grid_clear(flagEaseGrid,0);
ds_grid_clear(flagGrid,0);
ds_grid_clear(mineGrid,0);
ds_grid_clear(nearGrid,0);
scr_place_mines(gridMines);
scr_calculate_grid_near();
won = false;
lost = false;
resetting = false;
hideOnReset = false;
hideOnResetTimer = 0;
wonTimer = 0;
lostTimer = 0;
gameplayTime = 0;
timerX = 0;
minesLeft = gridMines;
updateDrawing = true;